import turtle

def draw_square(x, y, size, color):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.color(color)
    turtle.begin_fill()
    for _ in range(4):
        turtle.forward(size)
        turtle.right(90)
    turtle.end_fill()

heart_pixels = [
    " 11  11 ",
    "11111111",
    "11111111",
    "11111111",
    " 111111 ",
    "  1111  ",
    "   11   ",
    "    1   "
]

pixel_size = 20
start_x = -80
start_y = 80

turtle.speed(0)
turtle.bgcolor("black")

for row_idx, row in enumerate(heart_pixels):
    for col_idx, char in enumerate(row):
        if char == '1':
            x = start_x + col_idx * pixel_size
            y = start_y - row_idx * pixel_size
            draw_square(x, y, pixel_size, "red")

turtle.hideturtle()
turtle.done()
